[package]
name = "bill_hash_exercise"
version = "0.1.0"
authors = ["laboon <laboon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
